# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcbfb6eae53a992ffe93c522bcabaed53c8375c1436cfe755272fd9d74bb248c581e1369c841e0cc575a739b0454edca30e94c039a590e7a1eb72f027f9d64e5

test:
  secret_key_base: 436951b803f931d7aeffd7a1e34eb1b028c2c665dfb4bef1383f764bcc93e6e235157fc662dd664862265c05d5c7ca608ba0d3c47a7f0f376d09896cfcb46bdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
